import type { Channel, FeedVideo } from "./types";

export const demoChannels: Channel[] = [
  { id: "demo-tech", name: "Tech Vandaag", url: "#", avatar: "", autoDownload: false, videoQuality: "1080" },
  { id: "demo-buiten", name: "Studio Buiten", url: "#", avatar: "", autoDownload: false, videoQuality: "1080" },
  { id: "demo-keuken", name: "De Kleine Keuken", url: "#", avatar: "", autoDownload: true, videoQuality: "720" },
  { id: "demo-maken", name: "Gewoon Maken", url: "#", avatar: "", autoDownload: false, videoQuality: "1080" },
  { id: "demo-verhaal", name: "Lang Verhaal Kort", url: "#", avatar: "", autoDownload: false, videoQuality: "1080" },
];

const now = Date.now();
const hoursAgo = (hours: number) => new Date(now - hours * 60 * 60 * 1000).toISOString();

export const demoVideos: FeedVideo[] = [
  {
    id: "dmo00000001",
    channelId: "demo-tech",
    channelName: "Tech Vandaag",
    channelAvatar: "",
    title: "Waarom deze kleine thuisserver verrassend veel aankan",
    thumbnail: "",
    publishedAt: hoursAgo(1),
    duration: 1138,
    downloaded: false,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000002",
    channelId: "demo-buiten",
    channelName: "Studio Buiten",
    channelAvatar: "",
    title: "Een stille ochtend aan de Nederlandse kust",
    thumbnail: "",
    publishedAt: hoursAgo(3),
    duration: 824,
    downloaded: true,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000003",
    channelId: "demo-keuken",
    channelName: "De Kleine Keuken",
    channelAvatar: "",
    title: "Pasta met vijf ingrediënten die altijd lukt",
    thumbnail: "",
    publishedAt: hoursAgo(7),
    duration: 664,
    downloaded: false,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000004",
    channelId: "demo-maken",
    channelName: "Gewoon Maken",
    channelAvatar: "",
    title: "Ik bouwde een minimalistische kast zonder schroeven",
    thumbnail: "",
    publishedAt: hoursAgo(13),
    duration: 1452,
    downloaded: true,
    missing: false,
    watched: true,
  },
  {
    id: "dmo00000005",
    channelId: "demo-verhaal",
    channelName: "Lang Verhaal Kort",
    channelAvatar: "",
    title: "Hoe één vergeten spoorlijn een hele stad veranderde",
    thumbnail: "",
    publishedAt: hoursAgo(21),
    duration: 1028,
    downloaded: false,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000006",
    channelId: "demo-tech",
    channelName: "Tech Vandaag",
    channelAvatar: "",
    title: "Mijn favoriete self-hosted apps na één jaar",
    thumbnail: "",
    publishedAt: hoursAgo(28),
    duration: 1275,
    downloaded: true,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000007",
    channelId: "demo-buiten",
    channelName: "Studio Buiten",
    channelAvatar: "",
    title: "Dwars door de duinen: de route die bijna niemand kent",
    thumbnail: "",
    publishedAt: hoursAgo(39),
    duration: 934,
    downloaded: false,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000008",
    channelId: "demo-keuken",
    channelName: "De Kleine Keuken",
    channelAvatar: "",
    title: "Brood bakken zonder ingewikkeld gedoe",
    thumbnail: "",
    publishedAt: hoursAgo(52),
    duration: 756,
    downloaded: true,
    missing: false,
    watched: true,
  },
];
