import type { Channel, FeedVideo } from "./types";

export const demoChannels: Channel[] = [
  { id: "demo-tech", name: "Today in Tech", url: "#", avatar: "", autoDownload: false, videoQuality: "1080" },
  { id: "demo-outdoors", name: "Outside Studio", url: "#", avatar: "", autoDownload: false, videoQuality: "1080" },
  { id: "demo-kitchen", name: "Small Kitchen", url: "#", avatar: "", autoDownload: true, videoQuality: "720" },
  { id: "demo-making", name: "Simply Made", url: "#", avatar: "", autoDownload: false, videoQuality: "1080" },
  { id: "demo-stories", name: "Short Long Story", url: "#", avatar: "", autoDownload: false, videoQuality: "1080" },
];

const now = Date.now();
const hoursAgo = (hours: number) => new Date(now - hours * 60 * 60 * 1000).toISOString();

export const demoVideos: FeedVideo[] = [
  {
    id: "dmo00000001",
    channelId: "demo-tech",
    channelName: "Today in Tech",
    channelAvatar: "",
    title: "Why this small home server can handle more than expected",
    thumbnail: "",
    publishedAt: hoursAgo(1),
    duration: 1138,
    downloaded: false,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000002",
    channelId: "demo-outdoors",
    channelName: "Outside Studio",
    channelAvatar: "",
    title: "A quiet morning on the Dutch coast",
    thumbnail: "",
    publishedAt: hoursAgo(3),
    duration: 824,
    downloaded: true,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000003",
    channelId: "demo-kitchen",
    channelName: "Small Kitchen",
    channelAvatar: "",
    title: "Five-ingredient pasta that always works",
    thumbnail: "",
    publishedAt: hoursAgo(7),
    duration: 664,
    downloaded: false,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000004",
    channelId: "demo-making",
    channelName: "Simply Made",
    channelAvatar: "",
    title: "I built a minimalist cabinet without screws",
    thumbnail: "",
    publishedAt: hoursAgo(13),
    duration: 1452,
    downloaded: true,
    missing: false,
    watched: true,
  },
  {
    id: "dmo00000005",
    channelId: "demo-stories",
    channelName: "Short Long Story",
    channelAvatar: "",
    title: "How one forgotten railway changed an entire city",
    thumbnail: "",
    publishedAt: hoursAgo(21),
    duration: 1028,
    downloaded: false,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000006",
    channelId: "demo-tech",
    channelName: "Today in Tech",
    channelAvatar: "",
    title: "My favorite self-hosted apps after one year",
    thumbnail: "",
    publishedAt: hoursAgo(28),
    duration: 1275,
    downloaded: true,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000007",
    channelId: "demo-outdoors",
    channelName: "Outside Studio",
    channelAvatar: "",
    title: "Across the dunes: the route almost nobody knows",
    thumbnail: "",
    publishedAt: hoursAgo(39),
    duration: 934,
    downloaded: false,
    missing: false,
    watched: false,
  },
  {
    id: "dmo00000008",
    channelId: "demo-kitchen",
    channelName: "Small Kitchen",
    channelAvatar: "",
    title: "Baking bread without making it complicated",
    thumbnail: "",
    publishedAt: hoursAgo(52),
    duration: 756,
    downloaded: true,
    missing: false,
    watched: true,
  },
];
